version: "0.1"
services:
  process:
    image: alfresco/process-services:1.10.0
    environment:
      ACTIVITI_DATASOURCE_USERNAME: alfresco
      ACTIVITI_DATASOURCE_PASSWORD: alfresco
      ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
      ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/activiti?characterEncoding=UTF-8'
      ACTIVITI_CSRF_DISABLED: 'true'
      ACTIVITI_CORS_ENABLED: 'true'
      ACTIVITI_ES_SERVER_TYPE: client
      ACTIVITI_ES_DISCOVERY_HOSTS: elasticsearch:9300
      ACTIVITI_ES_CLUSTER_NAME: elasticsearch
    volumes:
      - "~/.activiti/enterprise-license:/root/.activiti/enterprise-license/:ro"
      - ./activiti-app.properties:/usr/share/tomcat/lib/activiti-app.properties
      - ./transform.lic:/usr/share/tomcat/lib/transform.lic
      - ./psdata:/usr/local/data/
    ports:
      - 80:8080
    links:
      - elasticsearch:elasticsearch
      - postgres:postgres
    depends_on:
      - elasticsearch
      - postgres
 
  elasticsearch:
    image: elasticsearch:1.7.3
 
  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: activiti
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  activitiadmin:
    image: alfresco/process-services-admin:1.10.0
    environment:
      ACTIVITI_ADMIN_DATASOURCE_DRIVER: org.postgres.Driver
      ACTIVITI_ADMIN_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      ACTIVITI_ADMIN_REST_APP_HOST: process
      ACTIVITI_ADMIN_REST_APP_PORT: 80
      ACTIVITI_ADMIN_REST_APP_USERNAME: admin@app.activiti.com
      ACTIVITI_ADMIN_REST_APP_PASSWORD: admin
    ports:
      -8080:8080
    links:
      - process:process
    depends_on:
      - process 
